### ISSUE TITLE
Uncaught TypeError: SSH2 is not a constructor

### ISSUE THREAD

**Issue by SimplySeth** [morassman/atom-commander#106]
[Enter steps to reproduce:]

1.  Install Atom commander
2. Begin adding new server
3.  Click `Test` button

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.12.3

### Stack Trace

Uncaught TypeError: SSH2 is not a constructor

```
At /Users/reinose/.atom/packages/atom-commander/lib/fs/ftp/sftp-session.coffee:78

TypeError: SSH2 is not a constructor
    at SFTPSession.module.exports.SFTPSession.connectWith (/packages/atom-commander/lib/fs/ftp/sftp-session.coffee:78:13)
    at SFTPSession.module.exports.SFTPSession.connect (/packages/atom-commander/lib/fs/ftp/sftp-session.coffee:50:8)
    at SFTPFileSystem.module.exports.SFTPFileSystem.connectImpl (/packages/atom-commander/lib/fs/ftp/sftp-filesystem.coffee:38:14)
    at SFTPFileSystem.module.exports.VFileSystem.connect (/packages/atom-commander/lib/fs/vfilesystem.coffee:90:8)
    at SFTPDialog.module.exports.SFTPDialog.test (/packages/atom-commander/lib/dialogs/sftp-dialog.coffee:399:8)
    at /packages/atom-commander/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/atom-commander/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/atom-commander/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:51.3.0 core:backspace (input.hidden-input)
     -5:43.7.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  6x -2:32.9.0 core:backspace (input.hidden-input)
     -1:39.3.0 atom-commander:toggle-visible (div.panels-item)
     -0:33.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-commander 0.12.3 
atom-material-syntax 1.0.8 
comment-commander 0.2.0 
jellybeans-syntax 0.7.0 
markdown-commander 0.1.1 
vim-mode-plus 1.36.6 
vim-mode-plus-macros 0.1.2 
```

**Comment by SeanAUS120** [comment]
I have the same error on a fresh install of Atom. 
I can't connect to any servers now. 



[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.12.3


### Stack Trace

Uncaught TypeError: SSH2 is not a constructor

```
At C:\Users\Sean OBrien\.atom\packages\atom-commander\lib\fs\ftp\sftp-session.coffee:78

TypeError: SSH2 is not a constructor
    at SFTPSession.module.exports.SFTPSession.connectWith (/packages/atom-commander/lib/fs/ftp/sftp-session.coffee:78:13)
    at SFTPSession.module.exports.SFTPSession.connect (/packages/atom-commander/lib/fs/ftp/sftp-session.coffee:42:8)
    at SFTPFileSystem.module.exports.SFTPFileSystem.connectImpl (/packages/atom-commander/lib/fs/ftp/sftp-filesystem.coffee:38:14)
    at SFTPFileSystem.module.exports.VFileSystem.connect (/packages/atom-commander/lib/fs/vfilesystem.coffee:90:8)
    at SFTPDialog.module.exports.SFTPDialog.test (/packages/atom-commander/lib/dialogs/sftp-dialog.coffee:399:8)
    at /packages/atom-commander/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/atom-commander/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/atom-commander/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:17.3.0 atom-commander:edit-server (span.syntax--text.syntax--plain.syntax--null-grammar)
```

### Non-Core Packages

```
atom-commander 0.12.3 
atom-minify 0.8.0 
```
