### ISSUE TITLE
Uncaught TypeError: decoration.getMarker(...).getPixelRange is not a function

### ISSUE THREAD

**Issue by azghanvi** [morassman/atom-commander#18]
Steps

1. Connect to server using ftp / sftp
2. click local file and remote, then right click->compare
3. click on editor code, it will throw error

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package, v0.5.0

### Stack Trace

Uncaught TypeError: decoration.getMarker(...).getPixelRange is not a function

```
At /C:/Users/Home/.atom/packages/atom-commander/lib/views/diff/diff-view.coffee:166

TypeError: decoration.getMarker(...).getPixelRange is not a function
    at DiffView.module.exports.DiffView.getDecorationAtPixelY (file:///C:/Users/Home/.atom/packages/atom-commander/lib/views/diff/diff-view.coffee:129:43)
    at DiffView.module.exports.DiffView.handleMouseDown (file:///C:/Users/Home/.atom/packages/atom-commander/lib/views/diff/diff-view.coffee:86:19)
    at atom-text-editor.<anonymous> (file:///C:/Users/Home/.atom/packages/atom-commander/lib/views/diff/diff-view.coffee:46:8)
    at atom-text-editor.jQuery.event.dispatch (C:\Users\Home\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at atom-text-editor.elemData.handle (C:\Users\Home\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -5:09.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:41.7.0 atom-commander:add-server (div.block.content)
     -4:12.9.0 atom-commander:remove-server (atom-text-editor.editor.mini.directory-editor.is-focused)
     -4:02.8.0 atom-commander:add-server (atom-text-editor.editor.mini.directory-editor.is-focused)
  4x -3:57.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:08.6.0 atom-commander:compare-files (td.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "Remote-FTP"
    ],
    "openEmptyEditorOnStart": false
  },
  "atom-commander": {
    "uploadOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
atom-commander, v0.5.0

# Dev
No dev packages
```

**Comment by morassman** [comment]
This seems to be due to an API change in the latest version of Atom. The method that was used doesn't exist anymore. Another method in the new API was used, but an issue with determining the vertical scroll position seems to have slipped in as well. A workaround was added for now.
