### ISSUE TITLE
MacOSX Uncaught Error: ENOENT: no such file or directory, stat '/liveupdate1.conf'

### ISSUE THREAD

**Issue by SimplySeth** [morassman/atom-commander#60]
[Enter steps to reproduce below:]

1. Start Atom
2. Edit files.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package, v0.8.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/liveupdate1.conf'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/liveupdate1.conf'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at new LocalFile (/Users/reinose/.atom/packages/atom-commander/lib/fs/local/local-file.coffee:12:18)
    at LocalFileSystem.module.exports.LocalFileSystem.wrapEntries (/Users/reinose/.atom/packages/atom-commander/lib/fs/local/local-filesystem.coffee:121:25)
    at /Users/reinose/.atom/packages/atom-commander/lib/fs/local/local-filesystem.coffee:112:36
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:299:18
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/async/lib/async.js:188:33
    at addEntry (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:285:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:294:22
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
 21x -7:15.8.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
 16x -7:05.3.0 core:move-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -7:00.6.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  9x -6:51.3.0 core:move-right (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -6:37 core:move-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  8x -6:36.7.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -6:33.9.0 core:move-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -6:33.6.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  9x -6:33 core:move-right (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -6:31.3.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  8x -6:30.5.0 core:move-down (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  8x -6:28.6.0 core:move-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -6:23.3.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused.autocomplete-active)
  2x -5:40.5.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused.autocomplete-active)
     -5:37.2.0 core:save (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  8x -5:19 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
angular-2-typeScript-snippets, v0.6.3 (active)
angular-bootstrap, v1.0.1 (inactive)
angular2-snippets, v0.3.0 (active)
angular2-snippets-atom, v0.7.0 (active)
angularjs, v0.3.5 (active)
ansible-snippets, v0.2.0 (inactive)
ansible-vault, v0.3.1 (inactive)
atom-beautify, v0.29.14 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-commander, v0.8.5 (active)
autocomplete-angular-material, v0.4.0 (active)
autocomplete-ansible, v0.1.10 (active)
autocomplete-python, v1.8.24 (active)
bootstrap-3-snippetset, v0.0.6 (active)
chaps-angular-snippets, v0.2.4 (active)
git-plus, v6.3.0 (active)
language-ansible, v0.1.11 (active)
linter, v1.11.18 (active)
linter-ansible-linting, v1.2.1 (active)
markdown-writer, v2.6.2 (active)
python-debugger, v0.1.0 (active)
vim-mode-plus, v0.66.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by morassman** [comment]
Was `liveupdate1.conf` the file that you were editing at the time or did Atom Commander just happen to be showing the folder that contains that file? It looks like the file might have been deleted in the background. I'm just wondering if this was due to something done in Atom or from outside.

**Comment by SimplySeth** [comment]
I never dealt with a file called `liveupdate1.conf`
I never edited a file called `liveupdate1.conf`
Today, I just opened an empty editor and the error occurred.

**Comment by morassman** [comment]
The error indicates that the file `liveupdate1.conf` could not be found. I think I know what might have happened though. Atom Commander retrieves a list of all the files and folders that it needs to display. Then, for each file, it acquires more information about it (the file size, last date modified, etc.) What could have happened is that the file was in the initial list, but when more details of it was requested the file was already removed. `liveupdate1.conf` may be a temporary file that is used by another application, so it isn't necessarily associated with something that you were busy with.

The only think I can do is add better error handling to prevent such a thing from being a problem. I'll add more safe guards in the next update.

**Comment by morassman** [comment]
Hi. I released a small patch for this. It should prevent this from happening again.
