### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/AppData\Local\Temp\~DF35FE4973747811FD...

### ISSUE THREAD

**Issue by JoshLWScott** [morassman/atom-commander#62]
[Enter steps to reproduce:]

Every 30minutes or so, even when I'm not opening/closing files in Atom I get this error message.

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.8.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Josh Scott\AppData\Local\Temp\~DF35FE4973747811FD.TMP'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\Users\Josh Scott\AppData\Local\Temp\~DF35FE4973747811FD.TMP'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at /packages/atom-commander/lib/fs/local/local-file.coffee:12:18)
    at LocalFileSystem.module.exports.LocalFileSystem.wrapEntries (/packages/atom-commander/lib/fs/local/local-filesystem.coffee:121:25)
    at /packages/atom-commander/lib/fs/local/local-filesystem.coffee:112:36
    at /app.asar/node_modules/pathwatcher/lib/directory.js:302:18
    at /app.asar/node_modules/fs-plus/node_modules/async/lib/async.js:188:33
    at addEntry (/app.asar/node_modules/pathwatcher/lib/directory.js:288:18)
    at /app.asar/node_modules/pathwatcher/lib/directory.js:297:22
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-commander 0.8.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
behave-theme 1.6.0 
behave-theme 1.6.0 
blessed-dark-syntax 0.3.0 
format-sql 0.3.0 
genesis-ui 0.5.0 
grammar-token-limit 0.1.1 
jshint 1.8.6 
linter 1.11.22 
linter-php 1.3.1 
material-syntax 0.6.1 
multi-cursor 2.1.5 
nucleus-dark-ui 0.11.0 
php-analyser 0.2.0 
pigments 0.39.0 
qolor 0.4.1 
quick-query 0.9.0 
swackets 0.26.0 
tree-view-git-status 1.3.0 
```

**Comment by morassman** [comment]
I released a small patch that should take care of this. I couldn't reproduce this myself, but it seems that Atom Commander tries to read a file that doesn't exist anymore. In particular, I think it happens when such a file is a temporary file managed by the OS or another application.
