### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:/8891067751007788e0'

### ISSUE THREAD

**Issue by andreystarkov** [morassman/atom-commander#63]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.8.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\8891067751007788e0'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\8891067751007788e0'
  at Error (native)
  at fs.statSync (fs.js:992:18)
  at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
  at /packages/atom-commander/lib/fs/local/local-directory.coffee:13:18)
  at LocalFileSystem.module.exports.LocalFileSystem.wrapEntries (/packages/atom-commander/lib/fs/local/local-filesystem.coffee:119:25)
  at /packages/atom-commander/lib/fs/local/local-filesystem.coffee:112:36
  at /app.asar/node_modules/pathwatcher/lib/directory.js:302:18
  at /app.asar/node_modules/fs-plus/node_modules/async/lib/async.js:188:33
  at addEntry (/app.asar/node_modules/pathwatcher/lib/directory.js:288:18)
  at /app.asar/node_modules/pathwatcher/lib/directory.js:297:22
  at FSReqWrap.oncomplete (fs.js:123:15)

```

### Commands

```
     -8:48.1.0 core:paste (input.hidden-input)
     -8:46.9.0 docblockr:parse-tab (input.hidden-input)
     -8:46.9.0 snippets:next-tab-stop (input.hidden-input)
     -8:46.9.0 snippets:expand (input.hidden-input)
     -8:46.9.0 editor:indent (input.hidden-input)
     -8:46.4.0 docblockr:parse-tab (input.hidden-input)
     -8:46.4.0 snippets:next-tab-stop (input.hidden-input)
     -8:46.4.0 snippets:expand (input.hidden-input)
     -8:46.4.0 editor:indent (input.hidden-input)
  2x -8:31.6.0 core:save (input.hidden-input)
     -0:46.1.0 find-and-replace:show (input.hidden-input)
     -0:40.1.0 tabs:split-right (li.texteditor.tab.sortable.active.right-clicked)
     -0:09.8.0 tag:close-tag (p.)
     -0:03.5.0 find-and-replace:show (input.hidden-input)
     -0:01.2.0 core:confirm (input.hidden-input)
     -0:00.1.0 find-and-replace:find-next (input.hidden-input)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
accents-ui 1.2.0 
aligner-scss 1.1.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-commander 0.8.6 
atom-dark-fusion-syntax 2.0.3 
atom-lupa 0.7.32 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-panda-syntax 0.18.0 
atom-ternjs 0.17.2 
atom-wrap-in-tag 0.6.0 
auto-detect-indentation 1.3.0 
auto-update-plus 0.2.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.7 
autoupdate-packages 1.3.1 
awesome-material-syntax 0.6.0 
babel-react-syntax 1.2.0 
base16-atelierdune-dark-syntax 2.0.3 
base16-dark-syntax 0.1.0 
base16-eighties-dark 2.1.1 
base16-ocean-dark-spacegray 0.13.0 
base16-ocean-dark-syntax-theme 0.1.10 
browse 1.4.1 
build 0.67.0 
busy 0.7.0 
chameleon-dark-syntax 0.0.5 
color-picker 2.2.5 
ctrl-dir-scroll 0.2.2 
dark-bint-syntax undefined 
dark-flat-ui 1.2.4 
daylight-ui 0.2.2 
docblockr 0.9.1 
eclectic-syntax 0.2.1 
editorconfig 2.2.1 
envygeeks-file-icons 0.2.1 
es-identifier-highlight 0.4.3 
es6-javascript 1.0.0 
file-icons 2.0.15 
file-type-icons 1.3.3 
glacier-dark-ui 0.5.0 
highlight-selected 0.12.0 
hydra-syntax-theme 2.0.4 
js-refactor 0.7.5 
language-babel 2.54.1 
language-graphql 0.8.0 
language-graphql-lb 0.3.1 
language-javascript-jsx 0.3.7 
less-autocompile 1.0.0 
line-ending-converter 1.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-flow 5.5.0 
material 2.2.0 
material-design-syntax 1.8.0 
material-monokai-syntax 1.0.1 
material-ui 1.0.9 
min-ui 0.0.4 
minimal-syntax 0.20.2 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
multi-cursor 2.1.5 
nord-atom-ui 0.10.1 
northem-dark-atom-syntax 2.0.0 
now-syntax 0.2.4 
nucleus-dark-ui 0.11.0 
nuclide 0.206.0 
nuclide-format-js 0.0.36 
numix-ui 0.2.2 
oceanic-one-dark-syntax 2.0.0 
react 0.16.2 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.11 
set-syntax 0.3.2 
sublime 0.4.2 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.3 
sublime-word-navigation 0.2.0 
sublimify 0.5.0 
sync-settings 0.8.1 
tag 0.4.0 
text-manipulation 0.6.0 
tree-view-copy-relative-path 1.0.1 
tree-view-git-modified 0.7.1 
tree-view-search-bar 0.1.3 
```

**Comment by morassman** [comment]
I released a small patch that should take care of this. I couldn't reproduce this myself, but it seems that Atom Commander tries to read a file that doesn't exist anymore. In particular, I think it happens when such a file is a temporary file managed by the OS or another application.
