### ISSUE TITLE
Uncaught TypeError: this.parentDialog.getMain is not a function

### ISSUE THREAD

**Issue by appsassociates-dev** [morassman/atom-commander#74]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.9.0

### Stack Trace

Uncaught TypeError: this.parentDialog.getMain is not a function

```
At C:\Users\srinivas.kanduri\.atom\packages\atom-commander\lib\dialogs\sftp-dialog.coffee:369

TypeError: this.parentDialog.getMain is not a function
    at SFTPDialog.module.exports.SFTPDialog.test (/packages/atom-commander/lib/dialogs/sftp-dialog.coffee:369:43)
    at /packages/Remote-FTP/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/Remote-FTP/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -8:21.6.0 settings-view:open (div.tool-panel.tree-view)
     -8:12 atom-commander:toggle-visible (div.panels-item)
  2x -8:00.5.0 core:backspace (input.hidden-input)
  2x -7:57.6.0 core:confirm (input.hidden-input)
  5x -6:14.2.0 core:backspace (input.hidden-input)
     -6:07.1.0 core:confirm (input.hidden-input)
     -4:45.7.0 atom-commander:toggle-focus (input.hidden-input)
     -3:35.3.0 core:confirm (input.hidden-input)
     -3:08.9.0 atom-commander:add-server (td..directory.icon.icon-file-directory)
  2x -2:56.6.0 core:paste (input.hidden-input)
     -2:04.1.0 atom-commander:edit-server (div.atom-commander-list-view-scroller)
     -1:58.7.0 core:backspace (input.hidden-input)
  2x -1:33.7.0 core:paste (input.hidden-input)
 12x -1:21 core:backspace (input.hidden-input)
     -1:05.9.0 core:paste (input.hidden-input)
     -0:21.4.0 atom-commander:open-server (div.atom-commander-list-view-scroller)
```

### Non-Core Packages

```
atom-commander 0.9.0 
atom-ftp-editor 0.5.0 
atom-sync 0.7.3 
atomic-sync 0.6.4 
aurora-theme 1.2.2 
ftp-remote-edit 0.11.2 
gloom 0.6.4 
monokai-seti 0.9.0 
motepair 0.23.0 
remote-atom 1.3.10 
remote-atom-plus 0.1.0 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
SFTP-deployment 1.0.2 
```

**Comment by morassman** [comment]
Fixed in version 0.10.2
