### ISSUE TITLE
Error when trying to save file in editor that is located on Server

### ISSUE THREAD

**Issue by shantiscript** [morassman/atom-commander#81]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: 'atom-ftp-editor' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/sebastiangrede/.atom/packages/atom-ftp-editor/lib/main.js:115

TypeError: Cannot read property 'path' of undefined
    at Object.__uploadCurrent (/packages/atom-ftp-editor/lib/main.js:115:84)
    at HTMLDocument.__onsave (/packages/atom-ftp-editor/lib/main.js:95:21)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:56.7.0 core:save (input.hidden-input)
  2x -5:46.6.0 core:backspace (input.hidden-input)
  3x -5:44.2.0 core:save (input.hidden-input)
     -2:27.8.0 find-and-replace:show (tbody.atom-commander-list-view.list)
     -2:22.6.0 core:confirm (input.hidden-input)
  9x -2:20.8.0 core:backspace (input.hidden-input)
     -2:18 tree-view:toggle (input.hidden-input)
  2x -2:12.5.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -2:05.7.0 application:add-project-folder (input.hidden-input)
     -1:08.8.0 atom-commander:toggle-visible (div.panels-item)
     -0:02.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-commander 0.10.1 
```

**Comment by morassman** [comment]
The error says that it was thrown from atom-ftp-editor. One can also see that it is in the main.js file of that package:

```
/Users/sebastiangrede/.atom/packages/atom-ftp-editor/lib/main.js:115
```

You should rather log this at [atom-ftp-editor](https://atom.io/packages/atom-ftp-editor)
