### ISSUE TITLE
Uncaught Error: Unknown cipher

### ISSUE THREAD

**Issue by niskadevla** [morassman/atom-commander#99]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [atom-commander](https://github.com/morassman/atom-commander) package 0.12.0

### Stack Trace

Uncaught Error: Unknown cipher

```
At internal/crypto/cipher.js:79

Error: Unknown cipher
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at Object.createCipheriv (crypto.js:105:10)
    at Object.encrypt (/packages/atom-commander/node_modules/simple-encryptor/index.js:54:25)
    at Function.module.exports.Utils.encrypt (/packages/atom-commander/lib/utils.coffee:53:42)
    at FTPFileSystem.module.exports.FTPFileSystem.getSafeConfig (/packages/atom-commander/lib/fs/ftp/ftp-filesystem.coffee:109:31)
    at Server.module.exports.Server.serialize (/packages/atom-commander/lib/servers/server.coffee:41:24)
    at ServerManager.module.exports.ServerManager.serialize (/packages/atom-commander/lib/servers/server-manager.coffee:134:25)
    at Object.serialize (/packages/atom-commander/lib/atom-commander.coffee:235:38)
    at Object.saveState (/packages/atom-commander/lib/atom-commander.coffee:212:14)
    at Object.show (/packages/atom-commander/lib/atom-commander.coffee:330:6)
    at Object.toggle (/packages/atom-commander/lib/atom-commander.coffee:314:8)
    at /packages/atom-commander/lib/atom-commander.coffee:70:97)
    at CommandRegistry.handleCommandEvent (/snap/atom/241/usr/share/atom/resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (/snap/atom/241/usr/share/atom/resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (/snap/atom/241/usr/share/atom/resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (/snap/atom/241/usr/share/atom/resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -0:11.2.0 atom-commander:toggle-visible (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-commander 0.12.0 
atom-i18n 0.20.0 
color-picker 2.3.0 
emmet 2.4.3 
highlight-selected 0.16.0 
platformio-ide-terminal 2.9.4 
react 0.18.0 
```

**Comment by DMHG** [comment]
Hello. A colleague and I are experiencing the same error.

**Comment by SeanAUS120** [comment]
I am getting this same error as well. On all servers. 

```
Uncaught Error: Unknown cipher
internal/crypto/cipher.js:79
```

**Comment by PureEuphoria** [comment]
Yes I just began having this error myself, this morning.

**Comment by SeanAUS120** [comment]
Anyone solve? Cannot use Commander ever since :-(

**Comment by MannyLeal93** [comment]
The issue can be solved by changing "**aes256**" to "**aes-256-cbc**" at line 54 and line 101 in the index.js file.
File path: 
C:\Users\**Username**\.atom\packages\atom-commander\node_modules\simple-encryptor then to **index.js**
^ change the **Username** from the link above to the one for your PC.

**Comment by Andrew-Shal** [comment]
https://github.com/koltyakov/sp-pnp-node/issues/13#issuecomment-487562389

C:\Users\%profile%\.atom\packages\atom-commander\node_modules\simple-encryptor\index.js

use aes-256-cbc instead of aes256 in decrypt and encrypt

var cipher = crypto.createCipheriv('aes-256-cbc', cryptoKey, iv);
var decipher = crypto.createDecipheriv('aes-256-cbc', cryptoKey, iv);

**Comment by mbrughi** [comment]
Work for me!
Mac Osx Mojave
Modify this file:
/Users/nomeofuser/.atom/packages/atom-commander/node_modules/simple-encryptor/index.js

var cipher = crypto.createCipheriv('aes-256-cbc', cryptoKey, iv);
var decipher = crypto.createDecipheriv('aes-256-cbc', cryptoKey, iv);

Many Thanks to Andrew-Shal !!!!

**Comment by mbrughi** [comment]
Work also on Win 10
Modify the same file but in:
C:\Users\nameofuser\.atom\packages\atom-commander\node_modules\simple-encryptor
